package com.cmdbms.mapper;

import com.cmdbms.model.Argcoure;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ArgcoureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Argcoure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Argcoure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Argcoure> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Argcoure record);
}