package com.cmdbms.mapper;

import com.cmdbms.model.Argcoure;
import java.util.List;
import java.util.Map;

@Repository
public interface ArgcoureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Argcoure record);


    Argcoure selectByPrimaryKey(Integer id);

    List seleByClasAndTea(int teaId,int classId);

    List<Argcoure> selectAll();


    int updateByPrimaryKey(Argcoure record);


    /*查询教师姓名，课程名字，上课时间，上课教室，上课日期*/
    String selectTeaNameById(int id);
    String selectClassNameById(int id);


}