package com.cmdbms.mapper;

import com.cmdbms.model.Choocheck;
import java.util.List;

public interface ChoocheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Choocheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Choocheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Choocheck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Choocheck record);
}