package com.cmdbms.mapper;

import com.cmdbms.model.Choocheck;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ChoocheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Choocheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Choocheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Choocheck> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choo_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Choocheck record);
}