package com.cmdbms.mapper;

import com.cmdbms.model.Choosecourse;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ChoosecourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Choosecourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Choosecourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Choosecourse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_choose_course
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Choosecourse record);

    List<Choosecourse> selectStuApply();
}