package com.cmdbms.mapper;

import com.cmdbms.model.Classroomuse;
import java.util.List;

public interface ClassroomuseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Classroomuse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Classroomuse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Classroomuse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Classroomuse record);
}