package com.cmdbms.mapper;

import com.cmdbms.model.Classroomuse;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ClassroomuseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Classroomuse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Classroomuse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Classroomuse> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Classroomuse record);
}