package com.cmdbms.mapper;

import com.cmdbms.model.Cludmanger;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CludmangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Cludmanger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Cludmanger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Cludmanger> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Cludmanger record);
}