package com.cmdbms.mapper;

import com.cmdbms.model.Cludnumber;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CludnumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(@Param("studentId") Integer studentId, @Param("cludId") Integer cludId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Cludnumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Cludnumber selectByPrimaryKey(@Param("studentId") Integer studentId, @Param("cludId") Integer cludId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Cludnumber> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Cludnumber record);
}