package com.cmdbms.mapper;

import com.cmdbms.model.Cludmanger;
import java.util.List;

public interface CludmangerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Cludmanger record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Cludmanger selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Cludmanger> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Cludmanger record);
}