package com.cmdbms.mapper;

import com.cmdbms.model.Electric;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface ElectricMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer eleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Electric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Electric> selectByPrimaryKey(@Param(value = "elePlace")Integer elePlace,
                                      @Param(value = "eleMonth")Integer eleMonth,
                                      @Param(value = "eleYear")Integer eleYear,
                                      @Param(value = "elePlaceType")String elePlaceType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Electric> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Electric record);
}