package com.cmdbms.mapper;

import com.cmdbms.model.Examarrange;
import java.util.List;

public interface ExamarrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Examarrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Examarrange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Examarrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_exam_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Examarrange record);
}