package com.cmdbms.mapper;

import com.cmdbms.model.Financialproject;
import java.util.List;

public interface FinancialprojectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_project
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_project
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Financialproject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_project
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Financialproject selectByPrimaryKey(Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_project
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Financialproject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_project
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Financialproject record);
}