package com.cmdbms.mapper;

import com.cmdbms.model.Financialexpend;
import java.util.List;

public interface FinancialexpendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer finId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Financialexpend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Financialexpend selectByPrimaryKey(Integer finId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Financialexpend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Financialexpend record);
}