package com.cmdbms.mapper;

import com.cmdbms.model.Financialconsumables;
import java.util.List;

public interface FinancialconsumablesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_consumables
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer matId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_consumables
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Financialconsumables record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_consumables
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Financialconsumables selectByPrimaryKey(Integer matId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_consumables
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Financialconsumables> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_consumables
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Financialconsumables record);
}