package com.cmdbms.mapper;

import com.cmdbms.model.Financialwage;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface FinancialwageMapper {

    int deleteByPrimaryKey(Integer teaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_wage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insertWage(Financialwage record);

    int insert(Financialwage record);


    Financialwage selectByPrimaryKey(Integer teaId);


    List<Financialwage> selectAll();


    int updateByPrimaryKey(Financialwage record);
}