package com.cmdbms.mapper;

import com.cmdbms.model.Financialstudent;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface FinancialstudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(@Param("stuId") Integer stuId, @Param("proId") Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Financialstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Financialstudent selectByPrimaryKey(@Param("stuId") Integer stuId, @Param("proId") Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Financialstudent> selectAll();


    int updateByPrimaryKey(Financialstudent record);

    String selectProNameById(int proId);

    String selectStuNameById(int stuId);

    List<Financialstudent> selectStuSelf(int stuId);


}