package com.cmdbms.mapper;

import com.cmdbms.model.Financialstudent;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinancialstudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(@Param("stuId") Integer stuId, @Param("proId") Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Financialstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Financialstudent selectByPrimaryKey(@Param("stuId") Integer stuId, @Param("proId") Integer proId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Financialstudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Financialstudent record);
}