package com.cmdbms.mapper;

import com.cmdbms.model.Financialsubsidies;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface FinancialsubsidiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Financialsubsidies record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Financialsubsidies selectByPrimaryKey(Integer stuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Financialsubsidies> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Financialsubsidies record);
}