package com.cmdbms.mapper;

import com.cmdbms.model.Output;
import java.util.List;

public interface OutputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer outputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Output record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Output selectByPrimaryKey(Integer outputId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Output> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Output record);
}