package com.cmdbms.mapper;

import com.cmdbms.model.Purchasing;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PurchasingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer purId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Purchasing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Purchasing selectByPrimaryKey(Integer purId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Purchasing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Purchasing record);
}