package com.cmdbms.mapper;

import com.cmdbms.model.Purchasing;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Repository
public interface PurchasingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer purId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(@Param(value = "purId")Integer purId,
               @Param(value = "purEquipment")String purEquipment,
               @Param(value = "purProName")String purProName,
               @Param(value = "purTime") Date purTime,
               @Param(value = "purAmount")Integer purAmount,
               @Param(value = "purPrice")BigDecimal purPrice,
               @Param(value = "purMan")String purMan,
               @Param(value = "purAuditing")Boolean purAuditing);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Purchasing> selectByPrimaryKey(Boolean purAuditing);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Purchasing> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Purchasing record);
}