package com.cmdbms.mapper;

import com.cmdbms.model.Quitcoure;
import java.util.List;

public interface QuitcoureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Quitcoure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Quitcoure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Quitcoure> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Quitcoure record);
}