package com.cmdbms.mapper;

import com.cmdbms.model.Quitcoure;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface QuitcoureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Quitcoure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Quitcoure selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Quitcoure> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Quitcoure record);
}