package com.cmdbms.mapper;

import com.cmdbms.model.Reexam;
import java.util.List;

public interface ReexamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Reexam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Reexam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Reexam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Reexam record);
}