package com.cmdbms.mapper;

import com.cmdbms.model.Reexam;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReexamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Reexam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Reexam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Reexam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Reexam record);
}