package com.cmdbms.mapper;

import com.cmdbms.model.Spoilage;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SpoilageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer spoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Spoilage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Spoilage selectByPrimaryKey(Integer spoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Spoilage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Spoilage record);
}