package com.cmdbms.mapper;

import com.cmdbms.model.Staffsalary;
import java.util.List;

public interface StaffsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Staffsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Staffsalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Staffsalary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Staffsalary record);
}