package com.cmdbms.mapper;

import com.cmdbms.model.Staffsalary;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StaffsalaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Staffsalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Staffsalary selectByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Staffsalary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Staffsalary record);

    String selectAmountById(int id);

}