package com.cmdbms.mapper;

import com.cmdbms.model.Staffmsg;
import java.util.List;

public interface StaffmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Staffmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Staffmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Staffmsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Staffmsg record);
}