package com.cmdbms.mapper;

import com.cmdbms.model.Staffmsg;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface StaffmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Staffmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Staffmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Staffmsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Staffmsg record);
}