package com.cmdbms.mapper;

import com.cmdbms.model.Studentmsg;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface StudentmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Studentmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Studentmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Studentmsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Studentmsg record);
}