package com.cmdbms.mapper;

import com.cmdbms.model.Studentmsg;
import java.util.List;

public interface StudentmsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Studentmsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Studentmsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Studentmsg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student_msg
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Studentmsg record);
}