package com.cmdbms.mapper;

import com.cmdbms.model.Stuexamarrange;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StuexamarrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_exam_arrange
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_exam_arrange
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Stuexamarrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_exam_arrange
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Stuexamarrange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_exam_arrange
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Stuexamarrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_exam_arrange
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Stuexamarrange record);
}