package com.cmdbms.mapper;

import com.cmdbms.model.Teaarrange;
import java.util.List;

public interface TeaarrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Teaarrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    Teaarrange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Teaarrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Teaarrange record);
}