package com.cmdbms.mapper;

import com.cmdbms.model.Teaevaluate;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TeaevaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_evaluate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_evaluate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int insert(Teaevaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_evaluate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    Teaevaluate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_evaluate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    List<Teaevaluate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_evaluate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Teaevaluate record);
}