package com.cmdbms.mapper;

import com.cmdbms.model.Traininginfo;
import java.util.List;

public interface TraininginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_training_info
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int deleteByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_training_info
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int insert(Traininginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_training_info
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    Traininginfo selectByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_training_info
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    List<Traininginfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_training_info
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    int updateByPrimaryKey(Traininginfo record);
}