package com.cmdbms.mapper;

import com.cmdbms.model.Traininginfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TraininginfoMapper {

    int deleteByPrimaryKey(Integer staffId);


    int insert(Traininginfo record);


    Traininginfo selectByPrimaryKey(Integer staffId);


    List<Traininginfo> selectAll();

    List<Traininginfo> selectAllEnd();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_training_info
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    int updateByPrimaryKey(Traininginfo record);

    int insertEntryTraining(Traininginfo record);

}