package com.cmdbms.mapper;

import com.cmdbms.model.Unpass;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UnpassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Unpass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Unpass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Unpass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Unpass record);
}