package com.cmdbms.mapper;

import com.cmdbms.model.Violentinfo;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ViolentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Violentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Violentinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Violentinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Violentinfo record);
}