package com.cmdbms.mapper;

import com.cmdbms.model.Water;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface WaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int deleteByPrimaryKey(Integer watId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int insert(Water record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Water> selectByPrimaryKey(@Param(value = "watPlace") String watPlace,
                             @Param(value = "watMonth") Integer watMonth,
                             @Param(value = "watYear") Integer watYear,
                             @Param(value = "watPlaceType") String watPlaceType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    List<Water> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    int updateByPrimaryKey(Water record);
}