package com.cmdbms.mapper;

import com.cmdbms.model.Water;
import java.util.List;

public interface WaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int deleteByPrimaryKey(Integer watId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int insert(Water record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    Water selectByPrimaryKey(Integer watId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    List<Water> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    int updateByPrimaryKey(Water record);
}