spring:
  profiles:
    active: prod
  jackson:
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
    parser:
      allow_single_quotes: true
      allow_unquoted_control_chars: true
    serialization:
      fail_on_empty_beans: false
      indent_output: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      uri-encoding: UTF-8
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
  aop:
    proxy-target-class: true

mybatis:
  mapperLocations: classpath:mappers/*Mapper.xml
server:
  servlet:
    context-path: /api
