package com.cmdbms.model;

import java.util.Date;

public class Argcoure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.teacherId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.classId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.classroomId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer classroomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.courseTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date courseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.testTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date testTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.coureDate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer coureDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arg_coure.degree
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer degree;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Argcoure(Integer id, Integer teacherId, Integer classId, Integer classroomId, Date courseTime, Date testTime, Integer coureDate, Integer degree) {
        this.id = id;
        this.teacherId = teacherId;
        this.classId = classId;
        this.classroomId = classroomId;
        this.courseTime = courseTime;
        this.testTime = testTime;
        this.coureDate = coureDate;
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arg_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Argcoure() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.id
     *
     * @return the value of t_arg_coure.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.id
     *
     * @param id the value for t_arg_coure.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.teacherId
     *
     * @return the value of t_arg_coure.teacherId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.teacherId
     *
     * @param teacherId the value for t_arg_coure.teacherId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.classId
     *
     * @return the value of t_arg_coure.classId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.classId
     *
     * @param classId the value for t_arg_coure.classId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.classroomId
     *
     * @return the value of t_arg_coure.classroomId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getClassroomId() {
        return classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.classroomId
     *
     * @param classroomId the value for t_arg_coure.classroomId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setClassroomId(Integer classroomId) {
        this.classroomId = classroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.courseTime
     *
     * @return the value of t_arg_coure.courseTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getCourseTime() {
        return courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.courseTime
     *
     * @param courseTime the value for t_arg_coure.courseTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCourseTime(Date courseTime) {
        this.courseTime = courseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.testTime
     *
     * @return the value of t_arg_coure.testTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.testTime
     *
     * @param testTime the value for t_arg_coure.testTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.coureDate
     *
     * @return the value of t_arg_coure.coureDate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getCoureDate() {
        return coureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.coureDate
     *
     * @param coureDate the value for t_arg_coure.coureDate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCoureDate(Integer coureDate) {
        this.coureDate = coureDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arg_coure.degree
     *
     * @return the value of t_arg_coure.degree
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arg_coure.degree
     *
     * @param degree the value for t_arg_coure.degree
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }
}