package com.cmdbms.model;

import java.util.Date;

public class Check {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.cheId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer cheId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.cheTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date cheTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.chePlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String chePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.cheTruefalse
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Byte cheTruefalse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.cheEquipment
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String cheEquipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.cheAmount
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer cheAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.cheMan
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String cheMan;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Check(Integer cheId, Date cheTime, String chePlace, Byte cheTruefalse, String cheEquipment, Integer cheAmount, String cheMan) {
        this.cheId = cheId;
        this.cheTime = cheTime;
        this.chePlace = chePlace;
        this.cheTruefalse = cheTruefalse;
        this.cheEquipment = cheEquipment;
        this.cheAmount = cheAmount;
        this.cheMan = cheMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Check() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.cheId
     *
     * @return the value of t_check.cheId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getCheId() {
        return cheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.cheId
     *
     * @param cheId the value for t_check.cheId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCheId(Integer cheId) {
        this.cheId = cheId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.cheTime
     *
     * @return the value of t_check.cheTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getCheTime() {
        return cheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.cheTime
     *
     * @param cheTime the value for t_check.cheTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCheTime(Date cheTime) {
        this.cheTime = cheTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.chePlace
     *
     * @return the value of t_check.chePlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getChePlace() {
        return chePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.chePlace
     *
     * @param chePlace the value for t_check.chePlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setChePlace(String chePlace) {
        this.chePlace = chePlace == null ? null : chePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.cheTruefalse
     *
     * @return the value of t_check.cheTruefalse
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Byte getCheTruefalse() {
        return cheTruefalse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.cheTruefalse
     *
     * @param cheTruefalse the value for t_check.cheTruefalse
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCheTruefalse(Byte cheTruefalse) {
        this.cheTruefalse = cheTruefalse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.cheEquipment
     *
     * @return the value of t_check.cheEquipment
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getCheEquipment() {
        return cheEquipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.cheEquipment
     *
     * @param cheEquipment the value for t_check.cheEquipment
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCheEquipment(String cheEquipment) {
        this.cheEquipment = cheEquipment == null ? null : cheEquipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.cheAmount
     *
     * @return the value of t_check.cheAmount
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getCheAmount() {
        return cheAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.cheAmount
     *
     * @param cheAmount the value for t_check.cheAmount
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCheAmount(Integer cheAmount) {
        this.cheAmount = cheAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.cheMan
     *
     * @return the value of t_check.cheMan
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getCheMan() {
        return cheMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.cheMan
     *
     * @param cheMan the value for t_check.cheMan
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCheMan(String cheMan) {
        this.cheMan = cheMan == null ? null : cheMan.trim();
    }
}