package com.cmdbms.model;

import java.util.Date;

public class Classroomuse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.useClrId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer useClrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.useApplyTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date useApplyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.useClrTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date useClrTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.useAuditTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date useAuditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.useThrough
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Boolean useThrough;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom_use.useClrName
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String useClrName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Classroomuse(Integer id, Integer useClrId, Date useApplyTime, Date useClrTime, Date useAuditTime, Boolean useThrough, String useClrName) {
        this.id = id;
        this.useClrId = useClrId;
        this.useApplyTime = useApplyTime;
        this.useClrTime = useClrTime;
        this.useAuditTime = useAuditTime;
        this.useThrough = useThrough;
        this.useClrName = useClrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom_use
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Classroomuse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.id
     *
     * @return the value of t_classroom_use.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.id
     *
     * @param id the value for t_classroom_use.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.useClrId
     *
     * @return the value of t_classroom_use.useClrId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getUseClrId() {
        return useClrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.useClrId
     *
     * @param useClrId the value for t_classroom_use.useClrId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setUseClrId(Integer useClrId) {
        this.useClrId = useClrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.useApplyTime
     *
     * @return the value of t_classroom_use.useApplyTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getUseApplyTime() {
        return useApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.useApplyTime
     *
     * @param useApplyTime the value for t_classroom_use.useApplyTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setUseApplyTime(Date useApplyTime) {
        this.useApplyTime = useApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.useClrTime
     *
     * @return the value of t_classroom_use.useClrTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getUseClrTime() {
        return useClrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.useClrTime
     *
     * @param useClrTime the value for t_classroom_use.useClrTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setUseClrTime(Date useClrTime) {
        this.useClrTime = useClrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.useAuditTime
     *
     * @return the value of t_classroom_use.useAuditTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getUseAuditTime() {
        return useAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.useAuditTime
     *
     * @param useAuditTime the value for t_classroom_use.useAuditTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setUseAuditTime(Date useAuditTime) {
        this.useAuditTime = useAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.useThrough
     *
     * @return the value of t_classroom_use.useThrough
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Boolean getUseThrough() {
        return useThrough;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.useThrough
     *
     * @param useThrough the value for t_classroom_use.useThrough
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setUseThrough(Boolean useThrough) {
        this.useThrough = useThrough;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom_use.useClrName
     *
     * @return the value of t_classroom_use.useClrName
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getUseClrName() {
        return useClrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom_use.useClrName
     *
     * @param useClrName the value for t_classroom_use.useClrName
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setUseClrName(String useClrName) {
        this.useClrName = useClrName == null ? null : useClrName.trim();
    }
}