package com.cmdbms.model;

public class Classroom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.type
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.size
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_classroom.state
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Classroom(Integer id, String name, Integer type, String size, Integer state) {
        this.id = id;
        this.name = name;
        this.type = type;
        this.size = size;
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_classroom
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Classroom() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.id
     *
     * @return the value of t_classroom.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom.id
     *
     * @param id the value for t_classroom.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.name
     *
     * @return the value of t_classroom.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom.name
     *
     * @param name the value for t_classroom.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.type
     *
     * @return the value of t_classroom.type
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom.type
     *
     * @param type the value for t_classroom.type
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.size
     *
     * @return the value of t_classroom.size
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom.size
     *
     * @param size the value for t_classroom.size
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_classroom.state
     *
     * @return the value of t_classroom.state
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_classroom.state
     *
     * @param state the value for t_classroom.state
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}