package com.cmdbms.model;

import java.util.Date;

public class Cludmanger {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_manger.id
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_manger.name
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_manger.number
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_manger.declarationTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Date declarationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_manger.studentId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_manger.cludStatus
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer cludStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Cludmanger(Integer id, String name, Integer number, Date declarationTime, Integer studentId, Integer cludStatus) {
        this.id = id;
        this.name = name;
        this.number = number;
        this.declarationTime = declarationTime;
        this.studentId = studentId;
        this.cludStatus = cludStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_manger
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Cludmanger() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_manger.id
     *
     * @return the value of t_clud_manger.id
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_manger.id
     *
     * @param id the value for t_clud_manger.id
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_manger.name
     *
     * @return the value of t_clud_manger.name
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_manger.name
     *
     * @param name the value for t_clud_manger.name
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_manger.number
     *
     * @return the value of t_clud_manger.number
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_manger.number
     *
     * @param number the value for t_clud_manger.number
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_manger.declarationTime
     *
     * @return the value of t_clud_manger.declarationTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Date getDeclarationTime() {
        return declarationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_manger.declarationTime
     *
     * @param declarationTime the value for t_clud_manger.declarationTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setDeclarationTime(Date declarationTime) {
        this.declarationTime = declarationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_manger.studentId
     *
     * @return the value of t_clud_manger.studentId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_manger.studentId
     *
     * @param studentId the value for t_clud_manger.studentId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_manger.cludStatus
     *
     * @return the value of t_clud_manger.cludStatus
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getCludStatus() {
        return cludStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_manger.cludStatus
     *
     * @param cludStatus the value for t_clud_manger.cludStatus
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setCludStatus(Integer cludStatus) {
        this.cludStatus = cludStatus;
    }
}