package com.cmdbms.model;

import java.util.Date;

public class Cludnumber {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.studentId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.cludId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer cludId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.joinTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date joinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.exitTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date exitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.cludPositionId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer cludPositionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.joinApplication
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Byte joinApplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.exitApplication
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String exitApplication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_clud_number.voteStatus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer voteStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Cludnumber(Integer studentId, Integer cludId, Date joinTime, Date exitTime, Integer cludPositionId, Byte joinApplication, String exitApplication, Integer voteStatus) {
        this.studentId = studentId;
        this.cludId = cludId;
        this.joinTime = joinTime;
        this.exitTime = exitTime;
        this.cludPositionId = cludPositionId;
        this.joinApplication = joinApplication;
        this.exitApplication = exitApplication;
        this.voteStatus = voteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_clud_number
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Cludnumber() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.studentId
     *
     * @return the value of t_clud_number.studentId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.studentId
     *
     * @param studentId the value for t_clud_number.studentId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.cludId
     *
     * @return the value of t_clud_number.cludId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getCludId() {
        return cludId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.cludId
     *
     * @param cludId the value for t_clud_number.cludId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCludId(Integer cludId) {
        this.cludId = cludId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.joinTime
     *
     * @return the value of t_clud_number.joinTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.joinTime
     *
     * @param joinTime the value for t_clud_number.joinTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.exitTime
     *
     * @return the value of t_clud_number.exitTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getExitTime() {
        return exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.exitTime
     *
     * @param exitTime the value for t_clud_number.exitTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setExitTime(Date exitTime) {
        this.exitTime = exitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.cludPositionId
     *
     * @return the value of t_clud_number.cludPositionId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getCludPositionId() {
        return cludPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.cludPositionId
     *
     * @param cludPositionId the value for t_clud_number.cludPositionId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCludPositionId(Integer cludPositionId) {
        this.cludPositionId = cludPositionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.joinApplication
     *
     * @return the value of t_clud_number.joinApplication
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Byte getJoinApplication() {
        return joinApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.joinApplication
     *
     * @param joinApplication the value for t_clud_number.joinApplication
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setJoinApplication(Byte joinApplication) {
        this.joinApplication = joinApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.exitApplication
     *
     * @return the value of t_clud_number.exitApplication
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getExitApplication() {
        return exitApplication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.exitApplication
     *
     * @param exitApplication the value for t_clud_number.exitApplication
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setExitApplication(String exitApplication) {
        this.exitApplication = exitApplication == null ? null : exitApplication.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_clud_number.voteStatus
     *
     * @return the value of t_clud_number.voteStatus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getVoteStatus() {
        return voteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_clud_number.voteStatus
     *
     * @param voteStatus the value for t_clud_number.voteStatus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setVoteStatus(Integer voteStatus) {
        this.voteStatus = voteStatus;
    }
}