package com.cmdbms.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.period
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.credit
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer credit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.compulsory
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Boolean compulsory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.offlineTeach
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Boolean offlineTeach;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Course(Integer id, String name, Integer period, Integer credit, Boolean compulsory, Boolean offlineTeach) {
        this.id = id;
        this.name = name;
        this.period = period;
        this.credit = credit;
        this.compulsory = compulsory;
        this.offlineTeach = offlineTeach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Course() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.id
     *
     * @return the value of t_course.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.id
     *
     * @param id the value for t_course.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.name
     *
     * @return the value of t_course.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.name
     *
     * @param name the value for t_course.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.period
     *
     * @return the value of t_course.period
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.period
     *
     * @param period the value for t_course.period
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.credit
     *
     * @return the value of t_course.credit
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.credit
     *
     * @param credit the value for t_course.credit
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.compulsory
     *
     * @return the value of t_course.compulsory
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Boolean getCompulsory() {
        return compulsory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.compulsory
     *
     * @param compulsory the value for t_course.compulsory
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setCompulsory(Boolean compulsory) {
        this.compulsory = compulsory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.offlineTeach
     *
     * @return the value of t_course.offlineTeach
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Boolean getOfflineTeach() {
        return offlineTeach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.offlineTeach
     *
     * @param offlineTeach the value for t_course.offlineTeach
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOfflineTeach(Boolean offlineTeach) {
        this.offlineTeach = offlineTeach;
    }
}