package com.cmdbms.model;

import java.math.BigDecimal;

public class Electric {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer eleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.elePlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer elePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleQuantity
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private BigDecimal eleQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleMonth
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer eleMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleYear
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer eleYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.elePlaceType
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String elePlaceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Electric(Integer eleId, Integer elePlace, BigDecimal eleQuantity, Integer eleMonth, Integer eleYear, String elePlaceType) {
        this.eleId = eleId;
        this.elePlace = elePlace;
        this.eleQuantity = eleQuantity;
        this.eleMonth = eleMonth;
        this.eleYear = eleYear;
        this.elePlaceType = elePlaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Electric() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleId
     *
     * @return the value of t_electric.eleId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getEleId() {
        return eleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleId
     *
     * @param eleId the value for t_electric.eleId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setEleId(Integer eleId) {
        this.eleId = eleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.elePlace
     *
     * @return the value of t_electric.elePlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getElePlace() {
        return elePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.elePlace
     *
     * @param elePlace the value for t_electric.elePlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setElePlace(Integer elePlace) {
        this.elePlace = elePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleQuantity
     *
     * @return the value of t_electric.eleQuantity
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public BigDecimal getEleQuantity() {
        return eleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleQuantity
     *
     * @param eleQuantity the value for t_electric.eleQuantity
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setEleQuantity(BigDecimal eleQuantity) {
        this.eleQuantity = eleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleMonth
     *
     * @return the value of t_electric.eleMonth
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getEleMonth() {
        return eleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleMonth
     *
     * @param eleMonth the value for t_electric.eleMonth
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setEleMonth(Integer eleMonth) {
        this.eleMonth = eleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleYear
     *
     * @return the value of t_electric.eleYear
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getEleYear() {
        return eleYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleYear
     *
     * @param eleYear the value for t_electric.eleYear
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setEleYear(Integer eleYear) {
        this.eleYear = eleYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.elePlaceType
     *
     * @return the value of t_electric.elePlaceType
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getElePlaceType() {
        return elePlaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.elePlaceType
     *
     * @param elePlaceType the value for t_electric.elePlaceType
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setElePlaceType(String elePlaceType) {
        this.elePlaceType = elePlaceType == null ? null : elePlaceType.trim();
    }
}