package com.cmdbms.model;

public class Electric {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer eleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.elePlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String elePlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleQuantity
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Long eleQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_electric.eleTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String eleTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Electric(Integer eleId, String elePlace, Long eleQuantity, String eleTime) {
        this.eleId = eleId;
        this.elePlace = elePlace;
        this.eleQuantity = eleQuantity;
        this.eleTime = eleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_electric
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Electric() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleId
     *
     * @return the value of t_electric.eleId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getEleId() {
        return eleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleId
     *
     * @param eleId the value for t_electric.eleId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setEleId(Integer eleId) {
        this.eleId = eleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.elePlace
     *
     * @return the value of t_electric.elePlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getElePlace() {
        return elePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.elePlace
     *
     * @param elePlace the value for t_electric.elePlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setElePlace(String elePlace) {
        this.elePlace = elePlace == null ? null : elePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleQuantity
     *
     * @return the value of t_electric.eleQuantity
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Long getEleQuantity() {
        return eleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleQuantity
     *
     * @param eleQuantity the value for t_electric.eleQuantity
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setEleQuantity(Long eleQuantity) {
        this.eleQuantity = eleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_electric.eleTime
     *
     * @return the value of t_electric.eleTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getEleTime() {
        return eleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_electric.eleTime
     *
     * @param eleTime the value for t_electric.eleTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setEleTime(String eleTime) {
        this.eleTime = eleTime == null ? null : eleTime.trim();
    }
}