package com.cmdbms.model;

public class Financialsubsidies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuEthnic
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stuEthnic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuAdress
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stuAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiReason
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stiReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiGrade
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stiGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiFile
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stiFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiState
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String stiState;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Financialsubsidies(Integer stuId, String stuName, String stuEthnic, String stuAdress, String stiReason, String stiGrade, String stiFile, String stiState) {
        this.stuId = stuId;
        this.stuName = stuName;
        this.stuEthnic = stuEthnic;
        this.stuAdress = stuAdress;
        this.stiReason = stiReason;
        this.stiGrade = stiGrade;
        this.stiFile = stiFile;
        this.stiState = stiState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Financialsubsidies() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stuId
     *
     * @return the value of t_financial_subsidies.stuId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stuId
     *
     * @param stuId the value for t_financial_subsidies.stuId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stuName
     *
     * @return the value of t_financial_subsidies.stuName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stuName
     *
     * @param stuName the value for t_financial_subsidies.stuName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stuEthnic
     *
     * @return the value of t_financial_subsidies.stuEthnic
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStuEthnic() {
        return stuEthnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stuEthnic
     *
     * @param stuEthnic the value for t_financial_subsidies.stuEthnic
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStuEthnic(String stuEthnic) {
        this.stuEthnic = stuEthnic == null ? null : stuEthnic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stuAdress
     *
     * @return the value of t_financial_subsidies.stuAdress
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStuAdress() {
        return stuAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stuAdress
     *
     * @param stuAdress the value for t_financial_subsidies.stuAdress
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStuAdress(String stuAdress) {
        this.stuAdress = stuAdress == null ? null : stuAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stiReason
     *
     * @return the value of t_financial_subsidies.stiReason
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStiReason() {
        return stiReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stiReason
     *
     * @param stiReason the value for t_financial_subsidies.stiReason
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStiReason(String stiReason) {
        this.stiReason = stiReason == null ? null : stiReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stiGrade
     *
     * @return the value of t_financial_subsidies.stiGrade
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStiGrade() {
        return stiGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stiGrade
     *
     * @param stiGrade the value for t_financial_subsidies.stiGrade
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStiGrade(String stiGrade) {
        this.stiGrade = stiGrade == null ? null : stiGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stiFile
     *
     * @return the value of t_financial_subsidies.stiFile
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStiFile() {
        return stiFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stiFile
     *
     * @param stiFile the value for t_financial_subsidies.stiFile
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStiFile(String stiFile) {
        this.stiFile = stiFile == null ? null : stiFile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stiState
     *
     * @return the value of t_financial_subsidies.stiState
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getStiState() {
        return stiState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_subsidies.stiState
     *
     * @param stiState the value for t_financial_subsidies.stiState
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStiState(String stiState) {
        this.stiState = stiState == null ? null : stiState.trim();
    }
}