package com.cmdbms.model;

public class Financialexpend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_expend.finId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer finId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_expend.finName
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private String finName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_expend.finMoney
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private String finMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Financialexpend(Integer finId, String finName, String finMoney) {
        this.finId = finId;
        this.finName = finName;
        this.finMoney = finMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_expend
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Financialexpend() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_expend.finId
     *
     * @return the value of t_financial_expend.finId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getFinId() {
        return finId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_expend.finId
     *
     * @param finId the value for t_financial_expend.finId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setFinId(Integer finId) {
        this.finId = finId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_expend.finName
     *
     * @return the value of t_financial_expend.finName
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public String getFinName() {
        return finName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_expend.finName
     *
     * @param finName the value for t_financial_expend.finName
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setFinName(String finName) {
        this.finName = finName == null ? null : finName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_expend.finMoney
     *
     * @return the value of t_financial_expend.finMoney
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public String getFinMoney() {
        return finMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_expend.finMoney
     *
     * @param finMoney the value for t_financial_expend.finMoney
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setFinMoney(String finMoney) {
        this.finMoney = finMoney == null ? null : finMoney.trim();
    }
}