package com.cmdbms.model;

public class Financialwage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_wage.teaId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer teaId;


    private String teaPosition;


    private String teaTt;

    private String teaWages;

    private String teaBonus;

    private String teaFine;

    private String teaMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_wage.teaState
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String teaState;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_wage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Financialwage(Integer teaId, String teaPosition, String teaTt, String teaWages, String teaBonus, String teaFine, String teaMoney, String teaState) {
        this.teaId = teaId;
        this.teaPosition = teaPosition;
        this.teaTt = teaTt;
        this.teaWages = teaWages;
        this.teaBonus = teaBonus;
        this.teaFine = teaFine;
        this.teaMoney = teaMoney;
        this.teaState = teaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_wage
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Financialwage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_wage.teaId
     *
     * @return the value of t_financial_wage.teaId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaId
     *
     * @param teaId the value for t_financial_wage.teaId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaId(Integer teaId) {
        this.teaId = teaId;
    }

    public String getTeaPosition() {
        return teaPosition;
    }

    public void setTeaPosition(String teaPosition) {
        this.teaPosition = teaPosition == null ? null : teaPosition.trim();
    }

    public String getTeaTt() {
        return teaTt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaTt
     *
     * @param teaTt the value for t_financial_wage.teaTt
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaTt(String teaTt) {
        this.teaTt = teaTt == null ? null : teaTt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_wage.teaWages
     *
     * @return the value of t_financial_wage.teaWages
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getTeaWages() {
        return teaWages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaWages
     *
     * @param teaWages the value for t_financial_wage.teaWages
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaWages(String teaWages) {
        this.teaWages = teaWages == null ? null : teaWages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_wage.teaBonus
     *
     * @return the value of t_financial_wage.teaBonus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getTeaBonus() {
        return teaBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaBonus
     *
     * @param teaBonus the value for t_financial_wage.teaBonus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaBonus(String teaBonus) {
        this.teaBonus = teaBonus == null ? null : teaBonus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_wage.teaFine
     *
     * @return the value of t_financial_wage.teaFine
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getTeaFine() {
        return teaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaFine
     *
     * @param teaFine the value for t_financial_wage.teaFine
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaFine(String teaFine) {
        this.teaFine = teaFine == null ? null : teaFine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_wage.teaMoney
     *
     * @return the value of t_financial_wage.teaMoney
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getTeaMoney() {
        return teaMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaMoney
     *
     * @param teaMoney the value for t_financial_wage.teaMoney
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaMoney(String teaMoney) {
        this.teaMoney = teaMoney == null ? null : teaMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_wage.teaState
     *
     * @return the value of t_financial_wage.teaState
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getTeaState() {
        return teaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_wage.teaState
     *
     * @param teaState the value for t_financial_wage.teaState
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setTeaState(String teaState) {
        this.teaState = teaState == null ? null : teaState.trim();
    }
}