package com.cmdbms.model;

import java.util.Date;

public class Financialstudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.stuId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.proId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.proName
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.proMoney
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private String proMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.proEndTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Date proEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.proTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Date proTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_student.proState
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private String proState;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Financialstudent(Integer stuId, Integer proId, String proName, String proMoney, Date proEndTime, Date proTime, String proState) {
        this.stuId = stuId;
        this.proId = proId;
        this.proName = proName;
        this.proMoney = proMoney;
        this.proEndTime = proEndTime;
        this.proTime = proTime;
        this.proState = proState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_student
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Financialstudent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.stuId
     *
     * @return the value of t_financial_student.stuId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.stuId
     *
     * @param stuId the value for t_financial_student.stuId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.proId
     *
     * @return the value of t_financial_student.proId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.proId
     *
     * @param proId the value for t_financial_student.proId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.proName
     *
     * @return the value of t_financial_student.proName
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.proName
     *
     * @param proName the value for t_financial_student.proName
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.proMoney
     *
     * @return the value of t_financial_student.proMoney
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public String getProMoney() {
        return proMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.proMoney
     *
     * @param proMoney the value for t_financial_student.proMoney
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setProMoney(String proMoney) {
        this.proMoney = proMoney == null ? null : proMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.proEndTime
     *
     * @return the value of t_financial_student.proEndTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Date getProEndTime() {
        return proEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.proEndTime
     *
     * @param proEndTime the value for t_financial_student.proEndTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setProEndTime(Date proEndTime) {
        this.proEndTime = proEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.proTime
     *
     * @return the value of t_financial_student.proTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Date getProTime() {
        return proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.proTime
     *
     * @param proTime the value for t_financial_student.proTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setProTime(Date proTime) {
        this.proTime = proTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_student.proState
     *
     * @return the value of t_financial_student.proState
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public String getProState() {
        return proState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_financial_student.proState
     *
     * @param proState the value for t_financial_student.proState
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setProState(String proState) {
        this.proState = proState == null ? null : proState.trim();
    }
}