package com.cmdbms.model;

public class Financialsubsidies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuName
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuEthnic
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String stuEthnic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stuAdress
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String stuAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiReason
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String stiReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiGrade
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String stiGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_financial_subsidies.stiFile
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */

    private String stiState;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Financialsubsidies(Integer stuId, String stuName, String stuEthnic, String stuAdress, String stiReason, String stiGrade, String stiState) {
        this.stuId = stuId;
        this.stuName = stuName;
        this.stuEthnic = stuEthnic;
        this.stuAdress = stuAdress;
        this.stiReason = stiReason;
        this.stiGrade = stiGrade;
        this.stiState = stiState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_financial_subsidies
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Financialsubsidies() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_financial_subsidies.stuId
     *
     * @return the value of t_financial_subsidies.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    public String getStuName() {
        return stuName;
    }

    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    public String getStuEthnic() {
        return stuEthnic;
    }

    public void setStuEthnic(String stuEthnic) {
        this.stuEthnic = stuEthnic == null ? null : stuEthnic.trim();
    }

    public String getStuAdress() {
        return stuAdress;
    }

    public void setStuAdress(String stuAdress) {
        this.stuAdress = stuAdress == null ? null : stuAdress.trim();
    }

    public String getStiReason() {
        return stiReason;
    }

    public void setStiReason(String stiReason) {
        this.stiReason = stiReason == null ? null : stiReason.trim();
    }

    public String getStiGrade() {
        return stiGrade;
    }

    public void setStiGrade(String stiGrade) {
        this.stiGrade = stiGrade == null ? null : stiGrade.trim();
    }

    public String getStiState() {
        return stiState;
    }

    public void setStiState(String stiState) {
        this.stiState = stiState == null ? null : stiState.trim();
    }
}