package com.cmdbms.model;

import java.util.Date;

public class Output {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer outputId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputEquipment
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String outputEquipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputSgelf
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String outputSgelf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputProName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String outputProName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Date outputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputPlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String outputPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputMan
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String outputMan;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Output(Integer outputId, String outputEquipment, String outputSgelf, String outputProName, Date outputTime, String outputPlace, String outputMan) {
        this.outputId = outputId;
        this.outputEquipment = outputEquipment;
        this.outputSgelf = outputSgelf;
        this.outputProName = outputProName;
        this.outputTime = outputTime;
        this.outputPlace = outputPlace;
        this.outputMan = outputMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Output() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputId
     *
     * @return the value of t_output.outputId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getOutputId() {
        return outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputId
     *
     * @param outputId the value for t_output.outputId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputId(Integer outputId) {
        this.outputId = outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputEquipment
     *
     * @return the value of t_output.outputEquipment
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getOutputEquipment() {
        return outputEquipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputEquipment
     *
     * @param outputEquipment the value for t_output.outputEquipment
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputEquipment(String outputEquipment) {
        this.outputEquipment = outputEquipment == null ? null : outputEquipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputSgelf
     *
     * @return the value of t_output.outputSgelf
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getOutputSgelf() {
        return outputSgelf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputSgelf
     *
     * @param outputSgelf the value for t_output.outputSgelf
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputSgelf(String outputSgelf) {
        this.outputSgelf = outputSgelf == null ? null : outputSgelf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputProName
     *
     * @return the value of t_output.outputProName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getOutputProName() {
        return outputProName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputProName
     *
     * @param outputProName the value for t_output.outputProName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputProName(String outputProName) {
        this.outputProName = outputProName == null ? null : outputProName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputTime
     *
     * @return the value of t_output.outputTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Date getOutputTime() {
        return outputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputTime
     *
     * @param outputTime the value for t_output.outputTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputTime(Date outputTime) {
        this.outputTime = outputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputPlace
     *
     * @return the value of t_output.outputPlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getOutputPlace() {
        return outputPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputPlace
     *
     * @param outputPlace the value for t_output.outputPlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputPlace(String outputPlace) {
        this.outputPlace = outputPlace == null ? null : outputPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputMan
     *
     * @return the value of t_output.outputMan
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getOutputMan() {
        return outputMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputMan
     *
     * @param outputMan the value for t_output.outputMan
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setOutputMan(String outputMan) {
        this.outputMan = outputMan == null ? null : outputMan.trim();
    }
}