package com.cmdbms.model;

import java.util.Date;

public class Output {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer outputId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputStoId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer outputStoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date outputTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputPlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String outputPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputMan
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String outputMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_output.outputNum
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer outputNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Output(Integer outputId, Integer outputStoId, Date outputTime, String outputPlace, String outputMan, Integer outputNum) {
        this.outputId = outputId;
        this.outputStoId = outputStoId;
        this.outputTime = outputTime;
        this.outputPlace = outputPlace;
        this.outputMan = outputMan;
        this.outputNum = outputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_output
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Output() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputId
     *
     * @return the value of t_output.outputId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getOutputId() {
        return outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputId
     *
     * @param outputId the value for t_output.outputId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOutputId(Integer outputId) {
        this.outputId = outputId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputStoId
     *
     * @return the value of t_output.outputStoId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getOutputStoId() {
        return outputStoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputStoId
     *
     * @param outputStoId the value for t_output.outputStoId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOutputStoId(Integer outputStoId) {
        this.outputStoId = outputStoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputTime
     *
     * @return the value of t_output.outputTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getOutputTime() {
        return outputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputTime
     *
     * @param outputTime the value for t_output.outputTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOutputTime(Date outputTime) {
        this.outputTime = outputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputPlace
     *
     * @return the value of t_output.outputPlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getOutputPlace() {
        return outputPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputPlace
     *
     * @param outputPlace the value for t_output.outputPlace
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOutputPlace(String outputPlace) {
        this.outputPlace = outputPlace == null ? null : outputPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputMan
     *
     * @return the value of t_output.outputMan
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getOutputMan() {
        return outputMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputMan
     *
     * @param outputMan the value for t_output.outputMan
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOutputMan(String outputMan) {
        this.outputMan = outputMan == null ? null : outputMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_output.outputNum
     *
     * @return the value of t_output.outputNum
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getOutputNum() {
        return outputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_output.outputNum
     *
     * @param outputNum the value for t_output.outputNum
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setOutputNum(Integer outputNum) {
        this.outputNum = outputNum;
    }
}