package com.cmdbms.model;

import java.math.BigDecimal;
import java.util.Date;

public class Purchasing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer purId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purEquipment
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String purEquipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purProName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String purProName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Date purTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purAmount
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer purAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purPrice
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private BigDecimal purPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purMan
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String purMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purInime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Date purInime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchasing.purAuditing
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String purAuditing;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Purchasing(Integer purId, String purEquipment, String purProName, Date purTime, Integer purAmount, BigDecimal purPrice, String purMan, Date purInime, String purAuditing) {
        this.purId = purId;
        this.purEquipment = purEquipment;
        this.purProName = purProName;
        this.purTime = purTime;
        this.purAmount = purAmount;
        this.purPrice = purPrice;
        this.purMan = purMan;
        this.purInime = purInime;
        this.purAuditing = purAuditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchasing
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Purchasing() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purId
     *
     * @return the value of t_purchasing.purId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getPurId() {
        return purId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purId
     *
     * @param purId the value for t_purchasing.purId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurId(Integer purId) {
        this.purId = purId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purEquipment
     *
     * @return the value of t_purchasing.purEquipment
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getPurEquipment() {
        return purEquipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purEquipment
     *
     * @param purEquipment the value for t_purchasing.purEquipment
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurEquipment(String purEquipment) {
        this.purEquipment = purEquipment == null ? null : purEquipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purProName
     *
     * @return the value of t_purchasing.purProName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getPurProName() {
        return purProName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purProName
     *
     * @param purProName the value for t_purchasing.purProName
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurProName(String purProName) {
        this.purProName = purProName == null ? null : purProName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purTime
     *
     * @return the value of t_purchasing.purTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Date getPurTime() {
        return purTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purTime
     *
     * @param purTime the value for t_purchasing.purTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurTime(Date purTime) {
        this.purTime = purTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purAmount
     *
     * @return the value of t_purchasing.purAmount
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getPurAmount() {
        return purAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purAmount
     *
     * @param purAmount the value for t_purchasing.purAmount
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurAmount(Integer purAmount) {
        this.purAmount = purAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purPrice
     *
     * @return the value of t_purchasing.purPrice
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public BigDecimal getPurPrice() {
        return purPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purPrice
     *
     * @param purPrice the value for t_purchasing.purPrice
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurPrice(BigDecimal purPrice) {
        this.purPrice = purPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purMan
     *
     * @return the value of t_purchasing.purMan
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getPurMan() {
        return purMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purMan
     *
     * @param purMan the value for t_purchasing.purMan
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurMan(String purMan) {
        this.purMan = purMan == null ? null : purMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purInime
     *
     * @return the value of t_purchasing.purInime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Date getPurInime() {
        return purInime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purInime
     *
     * @param purInime the value for t_purchasing.purInime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurInime(Date purInime) {
        this.purInime = purInime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchasing.purAuditing
     *
     * @return the value of t_purchasing.purAuditing
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getPurAuditing() {
        return purAuditing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchasing.purAuditing
     *
     * @param purAuditing the value for t_purchasing.purAuditing
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setPurAuditing(String purAuditing) {
        this.purAuditing = purAuditing == null ? null : purAuditing.trim();
    }
}