package com.cmdbms.model;

import java.util.Date;

public class Quitcheck {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_check.id
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_check.classId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_check.stuId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_check.applyTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_check.pass
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Boolean pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_check
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Quitcheck(Integer id, Integer classId, Integer stuId, Date applyTime, Boolean pass) {
        this.id = id;
        this.classId = classId;
        this.stuId = stuId;
        this.applyTime = applyTime;
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_check
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Quitcheck() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_check.id
     *
     * @return the value of t_quit_check.id
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_check.id
     *
     * @param id the value for t_quit_check.id
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_check.classId
     *
     * @return the value of t_quit_check.classId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_check.classId
     *
     * @param classId the value for t_quit_check.classId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_check.stuId
     *
     * @return the value of t_quit_check.stuId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_check.stuId
     *
     * @param stuId the value for t_quit_check.stuId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_check.applyTime
     *
     * @return the value of t_quit_check.applyTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_check.applyTime
     *
     * @param applyTime the value for t_quit_check.applyTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_check.pass
     *
     * @return the value of t_quit_check.pass
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Boolean getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_check.pass
     *
     * @param pass the value for t_quit_check.pass
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setPass(Boolean pass) {
        this.pass = pass;
    }
}