package com.cmdbms.model;

import java.util.Date;

public class Quitcoure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_coure.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_coure.classId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_coure.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_quit_coure.applyTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date applyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Quitcoure(Integer id, Integer classId, Integer stuId, Date applyTime) {
        this.id = id;
        this.classId = classId;
        this.stuId = stuId;
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quit_coure
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Quitcoure() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_coure.id
     *
     * @return the value of t_quit_coure.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_coure.id
     *
     * @param id the value for t_quit_coure.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_coure.classId
     *
     * @return the value of t_quit_coure.classId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_coure.classId
     *
     * @param classId the value for t_quit_coure.classId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_coure.stuId
     *
     * @return the value of t_quit_coure.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_coure.stuId
     *
     * @param stuId the value for t_quit_coure.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_quit_coure.applyTime
     *
     * @return the value of t_quit_coure.applyTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_quit_coure.applyTime
     *
     * @param applyTime the value for t_quit_coure.applyTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }
}