package com.cmdbms.model;

import java.util.Date;

public class Reexam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_re_exam.id
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_re_exam.subId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer subId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_re_exam.stuId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_re_exam.applyTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_re_exam.auditTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_re_exam.auditThrough
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Boolean auditThrough;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Reexam(Integer id, Integer subId, Integer stuId, Date applyTime, Date auditTime, Boolean auditThrough) {
        this.id = id;
        this.subId = subId;
        this.stuId = stuId;
        this.applyTime = applyTime;
        this.auditTime = auditTime;
        this.auditThrough = auditThrough;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_re_exam
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Reexam() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_re_exam.id
     *
     * @return the value of t_re_exam.id
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_re_exam.id
     *
     * @param id the value for t_re_exam.id
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_re_exam.subId
     *
     * @return the value of t_re_exam.subId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_re_exam.subId
     *
     * @param subId the value for t_re_exam.subId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_re_exam.stuId
     *
     * @return the value of t_re_exam.stuId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_re_exam.stuId
     *
     * @param stuId the value for t_re_exam.stuId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_re_exam.applyTime
     *
     * @return the value of t_re_exam.applyTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_re_exam.applyTime
     *
     * @param applyTime the value for t_re_exam.applyTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_re_exam.auditTime
     *
     * @return the value of t_re_exam.auditTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_re_exam.auditTime
     *
     * @param auditTime the value for t_re_exam.auditTime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_re_exam.auditThrough
     *
     * @return the value of t_re_exam.auditThrough
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Boolean getAuditThrough() {
        return auditThrough;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_re_exam.auditThrough
     *
     * @param auditThrough the value for t_re_exam.auditThrough
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setAuditThrough(Boolean auditThrough) {
        this.auditThrough = auditThrough;
    }
}