package com.cmdbms.model;

import java.util.Date;

public class Spoilage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spoilage.spoId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer spoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spoilage.spoEquipment
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private String spoEquipment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spoilage.spoAmount
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer spoAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spoilage.spoPlace
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private String spoPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_spoilage.spoTime
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Date spoTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Spoilage(Integer spoId, String spoEquipment, Integer spoAmount, String spoPlace, Date spoTime) {
        this.spoId = spoId;
        this.spoEquipment = spoEquipment;
        this.spoAmount = spoAmount;
        this.spoPlace = spoPlace;
        this.spoTime = spoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_spoilage
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Spoilage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spoilage.spoId
     *
     * @return the value of t_spoilage.spoId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getSpoId() {
        return spoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spoilage.spoId
     *
     * @param spoId the value for t_spoilage.spoId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setSpoId(Integer spoId) {
        this.spoId = spoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spoilage.spoEquipment
     *
     * @return the value of t_spoilage.spoEquipment
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public String getSpoEquipment() {
        return spoEquipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spoilage.spoEquipment
     *
     * @param spoEquipment the value for t_spoilage.spoEquipment
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setSpoEquipment(String spoEquipment) {
        this.spoEquipment = spoEquipment == null ? null : spoEquipment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spoilage.spoAmount
     *
     * @return the value of t_spoilage.spoAmount
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getSpoAmount() {
        return spoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spoilage.spoAmount
     *
     * @param spoAmount the value for t_spoilage.spoAmount
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setSpoAmount(Integer spoAmount) {
        this.spoAmount = spoAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spoilage.spoPlace
     *
     * @return the value of t_spoilage.spoPlace
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public String getSpoPlace() {
        return spoPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spoilage.spoPlace
     *
     * @param spoPlace the value for t_spoilage.spoPlace
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setSpoPlace(String spoPlace) {
        this.spoPlace = spoPlace == null ? null : spoPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_spoilage.spoTime
     *
     * @return the value of t_spoilage.spoTime
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Date getSpoTime() {
        return spoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_spoilage.spoTime
     *
     * @param spoTime the value for t_spoilage.spoTime
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setSpoTime(Date spoTime) {
        this.spoTime = spoTime;
    }
}