package com.cmdbms.model;

import java.util.Date;

public class Staffmsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.gender
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private byte[] gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.birthday
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.idCard
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.eduBackground
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String eduBackground;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.phone
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.mail
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.address
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.entryTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date entryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.politicalStatus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String politicalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_msg.salaryLevel
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String salaryLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Staffmsg(Integer id, String name, byte[] gender, Integer birthday, String idCard, String eduBackground, String phone, String mail, String address, Date entryTime, String politicalStatus, String salaryLevel) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.idCard = idCard;
        this.eduBackground = eduBackground;
        this.phone = phone;
        this.mail = mail;
        this.address = address;
        this.entryTime = entryTime;
        this.politicalStatus = politicalStatus;
        this.salaryLevel = salaryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_msg
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Staffmsg() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.id
     *
     * @return the value of t_staff_msg.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.id
     *
     * @param id the value for t_staff_msg.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.name
     *
     * @return the value of t_staff_msg.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.name
     *
     * @param name the value for t_staff_msg.name
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.gender
     *
     * @return the value of t_staff_msg.gender
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public byte[] getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.gender
     *
     * @param gender the value for t_staff_msg.gender
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGender(byte[] gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.birthday
     *
     * @return the value of t_staff_msg.birthday
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.birthday
     *
     * @param birthday the value for t_staff_msg.birthday
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.idCard
     *
     * @return the value of t_staff_msg.idCard
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.idCard
     *
     * @param idCard the value for t_staff_msg.idCard
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.eduBackground
     *
     * @return the value of t_staff_msg.eduBackground
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getEduBackground() {
        return eduBackground;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.eduBackground
     *
     * @param eduBackground the value for t_staff_msg.eduBackground
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setEduBackground(String eduBackground) {
        this.eduBackground = eduBackground == null ? null : eduBackground.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.phone
     *
     * @return the value of t_staff_msg.phone
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.phone
     *
     * @param phone the value for t_staff_msg.phone
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.mail
     *
     * @return the value of t_staff_msg.mail
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.mail
     *
     * @param mail the value for t_staff_msg.mail
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.address
     *
     * @return the value of t_staff_msg.address
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.address
     *
     * @param address the value for t_staff_msg.address
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.entryTime
     *
     * @return the value of t_staff_msg.entryTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.entryTime
     *
     * @param entryTime the value for t_staff_msg.entryTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.politicalStatus
     *
     * @return the value of t_staff_msg.politicalStatus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.politicalStatus
     *
     * @param politicalStatus the value for t_staff_msg.politicalStatus
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setPoliticalStatus(String politicalStatus) {
        this.politicalStatus = politicalStatus == null ? null : politicalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_msg.salaryLevel
     *
     * @return the value of t_staff_msg.salaryLevel
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getSalaryLevel() {
        return salaryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_msg.salaryLevel
     *
     * @param salaryLevel the value for t_staff_msg.salaryLevel
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setSalaryLevel(String salaryLevel) {
        this.salaryLevel = salaryLevel == null ? null : salaryLevel.trim();
    }
}