package com.cmdbms.model;

public class Staffsalary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_salary.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_salary.salaryAmount
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String salaryAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_staff_salary.staffId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer staffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Staffsalary(Integer id, String salaryAmount, Integer staffId) {
        this.id = id;
        this.salaryAmount = salaryAmount;
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_staff_salary
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Staffsalary() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_salary.id
     *
     * @return the value of t_staff_salary.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_salary.id
     *
     * @param id the value for t_staff_salary.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_salary.salaryAmount
     *
     * @return the value of t_staff_salary.salaryAmount
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getSalaryAmount() {
        return salaryAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_salary.salaryAmount
     *
     * @param salaryAmount the value for t_staff_salary.salaryAmount
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setSalaryAmount(String salaryAmount) {
        this.salaryAmount = salaryAmount == null ? null : salaryAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_staff_salary.staffId
     *
     * @return the value of t_staff_salary.staffId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_staff_salary.staffId
     *
     * @param staffId the value for t_staff_salary.staffId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }
}