package com.cmdbms.model;

import java.util.Date;

public class Stugrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeStuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer gradeStuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeSubId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer gradeSubId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeStu
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer gradeStu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeLimit
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date gradeLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeJudge
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Boolean gradeJudge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeAlterTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date gradeAlterTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stu_grade.gradeViolate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Boolean gradeViolate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_grade
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Stugrade(Integer id, Integer gradeStuId, Integer gradeSubId, Integer gradeStu, Date gradeLimit, Boolean gradeJudge, Date gradeAlterTime, Boolean gradeViolate) {
        this.id = id;
        this.gradeStuId = gradeStuId;
        this.gradeSubId = gradeSubId;
        this.gradeStu = gradeStu;
        this.gradeLimit = gradeLimit;
        this.gradeJudge = gradeJudge;
        this.gradeAlterTime = gradeAlterTime;
        this.gradeViolate = gradeViolate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stu_grade
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Stugrade() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.id
     *
     * @return the value of t_stu_grade.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.id
     *
     * @param id the value for t_stu_grade.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeStuId
     *
     * @return the value of t_stu_grade.gradeStuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getGradeStuId() {
        return gradeStuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeStuId
     *
     * @param gradeStuId the value for t_stu_grade.gradeStuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeStuId(Integer gradeStuId) {
        this.gradeStuId = gradeStuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeSubId
     *
     * @return the value of t_stu_grade.gradeSubId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getGradeSubId() {
        return gradeSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeSubId
     *
     * @param gradeSubId the value for t_stu_grade.gradeSubId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeSubId(Integer gradeSubId) {
        this.gradeSubId = gradeSubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeStu
     *
     * @return the value of t_stu_grade.gradeStu
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getGradeStu() {
        return gradeStu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeStu
     *
     * @param gradeStu the value for t_stu_grade.gradeStu
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeStu(Integer gradeStu) {
        this.gradeStu = gradeStu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeLimit
     *
     * @return the value of t_stu_grade.gradeLimit
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getGradeLimit() {
        return gradeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeLimit
     *
     * @param gradeLimit the value for t_stu_grade.gradeLimit
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeLimit(Date gradeLimit) {
        this.gradeLimit = gradeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeJudge
     *
     * @return the value of t_stu_grade.gradeJudge
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Boolean getGradeJudge() {
        return gradeJudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeJudge
     *
     * @param gradeJudge the value for t_stu_grade.gradeJudge
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeJudge(Boolean gradeJudge) {
        this.gradeJudge = gradeJudge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeAlterTime
     *
     * @return the value of t_stu_grade.gradeAlterTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getGradeAlterTime() {
        return gradeAlterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeAlterTime
     *
     * @param gradeAlterTime the value for t_stu_grade.gradeAlterTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeAlterTime(Date gradeAlterTime) {
        this.gradeAlterTime = gradeAlterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stu_grade.gradeViolate
     *
     * @return the value of t_stu_grade.gradeViolate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Boolean getGradeViolate() {
        return gradeViolate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stu_grade.gradeViolate
     *
     * @param gradeViolate the value for t_stu_grade.gradeViolate
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setGradeViolate(Boolean gradeViolate) {
        this.gradeViolate = gradeViolate;
    }
}