package com.cmdbms.model;

import java.util.Date;

public class Teaarghis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arg_his.id
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arg_his.classId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arg_his.teacherId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arg_his.cordYear
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Date cordYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arg_his.collegeTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    private Date collegeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arg_his
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Teaarghis(Integer id, Integer classId, Integer teacherId, Date cordYear, Date collegeTime) {
        this.id = id;
        this.classId = classId;
        this.teacherId = teacherId;
        this.cordYear = cordYear;
        this.collegeTime = collegeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arg_his
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Teaarghis() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arg_his.id
     *
     * @return the value of t_tea_arg_his.id
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arg_his.id
     *
     * @param id the value for t_tea_arg_his.id
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arg_his.classId
     *
     * @return the value of t_tea_arg_his.classId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arg_his.classId
     *
     * @param classId the value for t_tea_arg_his.classId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arg_his.teacherId
     *
     * @return the value of t_tea_arg_his.teacherId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arg_his.teacherId
     *
     * @param teacherId the value for t_tea_arg_his.teacherId
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arg_his.cordYear
     *
     * @return the value of t_tea_arg_his.cordYear
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Date getCordYear() {
        return cordYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arg_his.cordYear
     *
     * @param cordYear the value for t_tea_arg_his.cordYear
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setCordYear(Date cordYear) {
        this.cordYear = cordYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arg_his.collegeTime
     *
     * @return the value of t_tea_arg_his.collegeTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public Date getCollegeTime() {
        return collegeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arg_his.collegeTime
     *
     * @param collegeTime the value for t_tea_arg_his.collegeTime
     *
     * @mbg.generated Mon May 13 10:13:50 CST 2019
     */
    public void setCollegeTime(Date collegeTime) {
        this.collegeTime = collegeTime;
    }
}