package com.cmdbms.model;

public class Teaarrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arrange.id
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arrange.classId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tea_arrange.teacherId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer teacherId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Teaarrange(Integer id, Integer classId, Integer teacherId) {
        this.id = id;
        this.classId = classId;
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tea_arrange
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Teaarrange() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arrange.id
     *
     * @return the value of t_tea_arrange.id
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arrange.id
     *
     * @param id the value for t_tea_arrange.id
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arrange.classId
     *
     * @return the value of t_tea_arrange.classId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arrange.classId
     *
     * @param classId the value for t_tea_arrange.classId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tea_arrange.teacherId
     *
     * @return the value of t_tea_arrange.teacherId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tea_arrange.teacherId
     *
     * @param teacherId the value for t_tea_arrange.teacherId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }
}