package com.cmdbms.model;

public class Unpass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unpass.id
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unpass.subId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer subId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unpass.stuId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unpass.stuGrade
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private String stuGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_unpass.violent
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Boolean violent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Unpass(Integer id, Integer subId, Integer stuId, String stuGrade, Boolean violent) {
        this.id = id;
        this.subId = subId;
        this.stuId = stuId;
        this.stuGrade = stuGrade;
        this.violent = violent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unpass
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Unpass() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unpass.id
     *
     * @return the value of t_unpass.id
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unpass.id
     *
     * @param id the value for t_unpass.id
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unpass.subId
     *
     * @return the value of t_unpass.subId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unpass.subId
     *
     * @param subId the value for t_unpass.subId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unpass.stuId
     *
     * @return the value of t_unpass.stuId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unpass.stuId
     *
     * @param stuId the value for t_unpass.stuId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unpass.stuGrade
     *
     * @return the value of t_unpass.stuGrade
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public String getStuGrade() {
        return stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unpass.stuGrade
     *
     * @param stuGrade the value for t_unpass.stuGrade
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setStuGrade(String stuGrade) {
        this.stuGrade = stuGrade == null ? null : stuGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_unpass.violent
     *
     * @return the value of t_unpass.violent
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Boolean getViolent() {
        return violent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_unpass.violent
     *
     * @param violent the value for t_unpass.violent
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setViolent(Boolean violent) {
        this.violent = violent;
    }
}