package com.cmdbms.model;

import java.util.Date;

public class Violentinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_violent_info.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_violent_info.behavior
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String behavior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_violent_info.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_violent_info.vioContent
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private String vioContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_violent_info.violentLevel
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Integer violentLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_violent_info.regsterTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    private Date regsterTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Violentinfo(Integer id, String behavior, Integer stuId, String vioContent, Integer violentLevel, Date regsterTime) {
        this.id = id;
        this.behavior = behavior;
        this.stuId = stuId;
        this.vioContent = vioContent;
        this.violentLevel = violentLevel;
        this.regsterTime = regsterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_violent_info
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Violentinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_violent_info.id
     *
     * @return the value of t_violent_info.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_violent_info.id
     *
     * @param id the value for t_violent_info.id
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_violent_info.behavior
     *
     * @return the value of t_violent_info.behavior
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getBehavior() {
        return behavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_violent_info.behavior
     *
     * @param behavior the value for t_violent_info.behavior
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setBehavior(String behavior) {
        this.behavior = behavior == null ? null : behavior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_violent_info.stuId
     *
     * @return the value of t_violent_info.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_violent_info.stuId
     *
     * @param stuId the value for t_violent_info.stuId
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_violent_info.vioContent
     *
     * @return the value of t_violent_info.vioContent
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public String getVioContent() {
        return vioContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_violent_info.vioContent
     *
     * @param vioContent the value for t_violent_info.vioContent
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setVioContent(String vioContent) {
        this.vioContent = vioContent == null ? null : vioContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_violent_info.violentLevel
     *
     * @return the value of t_violent_info.violentLevel
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Integer getViolentLevel() {
        return violentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_violent_info.violentLevel
     *
     * @param violentLevel the value for t_violent_info.violentLevel
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setViolentLevel(Integer violentLevel) {
        this.violentLevel = violentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_violent_info.regsterTime
     *
     * @return the value of t_violent_info.regsterTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public Date getRegsterTime() {
        return regsterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_violent_info.regsterTime
     *
     * @param regsterTime the value for t_violent_info.regsterTime
     *
     * @mbg.generated Wed May 29 11:15:17 CST 2019
     */
    public void setRegsterTime(Date regsterTime) {
        this.regsterTime = regsterTime;
    }
}