package com.cmdbms.model;

public class Water {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer watId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watPlace
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private String watPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watQuantity
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Long watQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watMonth
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer watMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watYear
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private Integer watYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watPlaceType
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    private String watPlaceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Water(Integer watId, String watPlace, Long watQuantity, Integer watMonth, Integer watYear, String watPlaceType) {
        this.watId = watId;
        this.watPlace = watPlace;
        this.watQuantity = watQuantity;
        this.watMonth = watMonth;
        this.watYear = watYear;
        this.watPlaceType = watPlaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Water() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watId
     *
     * @return the value of t_water.watId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getWatId() {
        return watId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watId
     *
     * @param watId the value for t_water.watId
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setWatId(Integer watId) {
        this.watId = watId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watPlace
     *
     * @return the value of t_water.watPlace
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public String getWatPlace() {
        return watPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watPlace
     *
     * @param watPlace the value for t_water.watPlace
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setWatPlace(String watPlace) {
        this.watPlace = watPlace == null ? null : watPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watQuantity
     *
     * @return the value of t_water.watQuantity
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Long getWatQuantity() {
        return watQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watQuantity
     *
     * @param watQuantity the value for t_water.watQuantity
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setWatQuantity(Long watQuantity) {
        this.watQuantity = watQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watMonth
     *
     * @return the value of t_water.watMonth
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getWatMonth() {
        return watMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watMonth
     *
     * @param watMonth the value for t_water.watMonth
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setWatMonth(Integer watMonth) {
        this.watMonth = watMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watYear
     *
     * @return the value of t_water.watYear
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public Integer getWatYear() {
        return watYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watYear
     *
     * @param watYear the value for t_water.watYear
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setWatYear(Integer watYear) {
        this.watYear = watYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watPlaceType
     *
     * @return the value of t_water.watPlaceType
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public String getWatPlaceType() {
        return watPlaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watPlaceType
     *
     * @param watPlaceType the value for t_water.watPlaceType
     *
     * @mbg.generated Mon May 13 10:24:04 CST 2019
     */
    public void setWatPlaceType(String watPlaceType) {
        this.watPlaceType = watPlaceType == null ? null : watPlaceType.trim();
    }
}