package com.cmdbms.model;

public class Water {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Integer watId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watPlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String watPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.watQuantity
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private Long watQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_water.wattime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    private String wattime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Water(Integer watId, String watPlace, Long watQuantity, String wattime) {
        this.watId = watId;
        this.watPlace = watPlace;
        this.watQuantity = watQuantity;
        this.wattime = wattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_water
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Water() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watId
     *
     * @return the value of t_water.watId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Integer getWatId() {
        return watId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watId
     *
     * @param watId the value for t_water.watId
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setWatId(Integer watId) {
        this.watId = watId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watPlace
     *
     * @return the value of t_water.watPlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getWatPlace() {
        return watPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watPlace
     *
     * @param watPlace the value for t_water.watPlace
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setWatPlace(String watPlace) {
        this.watPlace = watPlace == null ? null : watPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.watQuantity
     *
     * @return the value of t_water.watQuantity
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public Long getWatQuantity() {
        return watQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.watQuantity
     *
     * @param watQuantity the value for t_water.watQuantity
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setWatQuantity(Long watQuantity) {
        this.watQuantity = watQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_water.wattime
     *
     * @return the value of t_water.wattime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public String getWattime() {
        return wattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_water.wattime
     *
     * @param wattime the value for t_water.wattime
     *
     * @mbg.generated Sat May 11 15:09:42 CST 2019
     */
    public void setWattime(String wattime) {
        this.wattime = wattime == null ? null : wattime.trim();
    }
}